# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oracle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oracle.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0coracle.proto\"K\n\x14MeterPushDataRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x11\n\tsignature\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\"{\n\x19\x46orecasterPushDataRequest\x12\x1d\n\tHousehold\x18\x01 \x01(\x0b\x32\n.Household\x12\x1d\n\ttimeframe\x18\x02 \x01(\x0b\x32\n.Timeframe\x12\x11\n\tsignature\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\"k\n\x15\x43\x61rbonPushDataRequest\x12\x11\n\tcommunity\x18\x01 \x01(\t\x12\x1d\n\ttimeframe\x18\x02 \x01(\x0b\x32\n.Timeframe\x12\x11\n\tsignature\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\"A\n\tTimeframe\x12\x10\n\x08\x64uration\x18\x01 \x01(\x03\x12\x11\n\tunixStart\x18\x02 \x01(\x03\x12\x0f\n\x07unixEnd\x18\x03 \x01(\x03\"\x1f\n\tHousehold\x12\x12\n\npublickKey\x18\x02 \x01(\t\"3\n\x05Reply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x19\n\x11\x64\x65rivedPublickKey\x18\x02 \x01(\t29\n\x05Meter\x12\x30\n\rMeterPushData\x12\x15.MeterPushDataRequest\x1a\x06.Reply\"\x00\x32H\n\nForecaster\x12:\n\x12\x46orecasterPushData\x12\x1a.ForecasterPushDataRequest\x1a\x06.Reply\"\x00\x32<\n\x06\x43\x61rbon\x12\x32\n\x0e\x43\x61rbonPushData\x12\x16.CarbonPushDataRequest\x1a\x06.Reply\"\x00\x62\x06proto3')
)




_METERPUSHDATAREQUEST = _descriptor.Descriptor(
  name='MeterPushDataRequest',
  full_name='MeterPushDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='MeterPushDataRequest.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='MeterPushDataRequest.signature', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='MeterPushDataRequest.value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=91,
)


_FORECASTERPUSHDATAREQUEST = _descriptor.Descriptor(
  name='ForecasterPushDataRequest',
  full_name='ForecasterPushDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Household', full_name='ForecasterPushDataRequest.Household', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeframe', full_name='ForecasterPushDataRequest.timeframe', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='ForecasterPushDataRequest.signature', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ForecasterPushDataRequest.value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=216,
)


_CARBONPUSHDATAREQUEST = _descriptor.Descriptor(
  name='CarbonPushDataRequest',
  full_name='CarbonPushDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='community', full_name='CarbonPushDataRequest.community', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeframe', full_name='CarbonPushDataRequest.timeframe', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='CarbonPushDataRequest.signature', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='CarbonPushDataRequest.value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=325,
)


_TIMEFRAME = _descriptor.Descriptor(
  name='Timeframe',
  full_name='Timeframe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='Timeframe.duration', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unixStart', full_name='Timeframe.unixStart', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unixEnd', full_name='Timeframe.unixEnd', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=392,
)


_HOUSEHOLD = _descriptor.Descriptor(
  name='Household',
  full_name='Household',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='publickKey', full_name='Household.publickKey', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=425,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='Reply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='derivedPublickKey', full_name='Reply.derivedPublickKey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=478,
)

_FORECASTERPUSHDATAREQUEST.fields_by_name['Household'].message_type = _HOUSEHOLD
_FORECASTERPUSHDATAREQUEST.fields_by_name['timeframe'].message_type = _TIMEFRAME
_CARBONPUSHDATAREQUEST.fields_by_name['timeframe'].message_type = _TIMEFRAME
DESCRIPTOR.message_types_by_name['MeterPushDataRequest'] = _METERPUSHDATAREQUEST
DESCRIPTOR.message_types_by_name['ForecasterPushDataRequest'] = _FORECASTERPUSHDATAREQUEST
DESCRIPTOR.message_types_by_name['CarbonPushDataRequest'] = _CARBONPUSHDATAREQUEST
DESCRIPTOR.message_types_by_name['Timeframe'] = _TIMEFRAME
DESCRIPTOR.message_types_by_name['Household'] = _HOUSEHOLD
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MeterPushDataRequest = _reflection.GeneratedProtocolMessageType('MeterPushDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _METERPUSHDATAREQUEST,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:MeterPushDataRequest)
  ))
_sym_db.RegisterMessage(MeterPushDataRequest)

ForecasterPushDataRequest = _reflection.GeneratedProtocolMessageType('ForecasterPushDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _FORECASTERPUSHDATAREQUEST,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:ForecasterPushDataRequest)
  ))
_sym_db.RegisterMessage(ForecasterPushDataRequest)

CarbonPushDataRequest = _reflection.GeneratedProtocolMessageType('CarbonPushDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _CARBONPUSHDATAREQUEST,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:CarbonPushDataRequest)
  ))
_sym_db.RegisterMessage(CarbonPushDataRequest)

Timeframe = _reflection.GeneratedProtocolMessageType('Timeframe', (_message.Message,), dict(
  DESCRIPTOR = _TIMEFRAME,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:Timeframe)
  ))
_sym_db.RegisterMessage(Timeframe)

Household = _reflection.GeneratedProtocolMessageType('Household', (_message.Message,), dict(
  DESCRIPTOR = _HOUSEHOLD,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:Household)
  ))
_sym_db.RegisterMessage(Household)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'oracle_pb2'
  # @@protoc_insertion_point(class_scope:Reply)
  ))
_sym_db.RegisterMessage(Reply)



_METER = _descriptor.ServiceDescriptor(
  name='Meter',
  full_name='Meter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=480,
  serialized_end=537,
  methods=[
  _descriptor.MethodDescriptor(
    name='MeterPushData',
    full_name='Meter.MeterPushData',
    index=0,
    containing_service=None,
    input_type=_METERPUSHDATAREQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METER)

DESCRIPTOR.services_by_name['Meter'] = _METER


_FORECASTER = _descriptor.ServiceDescriptor(
  name='Forecaster',
  full_name='Forecaster',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=539,
  serialized_end=611,
  methods=[
  _descriptor.MethodDescriptor(
    name='ForecasterPushData',
    full_name='Forecaster.ForecasterPushData',
    index=0,
    containing_service=None,
    input_type=_FORECASTERPUSHDATAREQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FORECASTER)

DESCRIPTOR.services_by_name['Forecaster'] = _FORECASTER


_CARBON = _descriptor.ServiceDescriptor(
  name='Carbon',
  full_name='Carbon',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=613,
  serialized_end=673,
  methods=[
  _descriptor.MethodDescriptor(
    name='CarbonPushData',
    full_name='Carbon.CarbonPushData',
    index=0,
    containing_service=None,
    input_type=_CARBONPUSHDATAREQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARBON)

DESCRIPTOR.services_by_name['Carbon'] = _CARBON

# @@protoc_insertion_point(module_scope)
